default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: blog2
  password: uiop7890

development:
  <<: *default
  database: rails_blog_development

test:
  <<: *default
  database: rails_blog_test

production:
  <<: *default
  database: rails_blog_production
  username: rails_blog
  password: <%= ENV["RAILS_BLOG_DATABASE_PASSWORD"] %>
